# ==========================================
# CONFIGURAÇÕES DO BANCO DE DADOS POSTGRESQL
# ==========================================

server.port=8081

# ==========================================
# CONFIGURAÇÕES DO BANCO DE DADOS POSTGRESQL
# ==========================================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/strideup}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:123456}

# ==========================================
# CONFIGURAÇÕES DO HIBERNATE (A MÁGICA)
# ==========================================

# Isso faz com que o Java crie as tabelas no banco automaticamente para você!
spring.jpa.hibernate.ddl-auto=update

# Mostra no console do IntelliJ os comandos SQL que o Java está executando por baixo dos panos
spring.jpa.show-sql=true

# Define o "sotaque" do SQL para o padrão exato do PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# CREDENCIAIS DA API DO STRAVA (OAUTH2)
# ==========================================
# Substitua pelos valores reais que o Strava lhe deu
# Credenciais da API do Strava (Obrigatório para o OAuth 2.0 funcionar)
strava.client.id=263398
strava.client.secret=6fe64d9820cf29db360e4322c4be3626ba00016a

# FORÇAR O SPRING BOOT E O HTML A USAREM UTF-8 (Acentos perfeitos)
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

# ADICIONE ISTO AO FINAL DA SUA URL DO BANCO DE DADOS (Exemplo do PostgreSQL)
# Exemplo: spring.datasource.url=jdbc:postgresql://localhost:5432/strideup?characterEncoding=UTF-8